### ISSUE TITLE
[Feat] : 모집글 리스트 / 정렬,전환 팝업 및 필터링 바

### ISSUE THREAD

**Issue by sujinyang00** [CoDEVumc/CoDEV_FrontEnd#5]
## 🛠 Issue
(프로젝트/스터디) 리스트 + (지역/분야)필터링 바 + (프로젝트/스터디)전환 팝업 + (지역/분야)정렬 팝업 

## 📝 To-do
- [ ] 프로젝트/스터디 모집글 리스트
- [ ] 플로팅 작성버튼
- [ ] 프로젝트/스터디 전환 팝업
- [ ] 지역/분야 필터링 바
- [ ] 지역/분야 정렬 팝업
