### ISSUE TITLE
[Feat] : 모집글 검색 및 커뮤니티 상세

### ISSUE THREAD

**Issue by Lee-hwansoo** [CoDEVumc/CoDEV_FrontEnd#55]
## 🛠 Issue
모집글 검색, 커뮤니티 상세

## 📝 To-do
- [x] 검색 레이아웃 구성
- [x] 검색 api 연결
- [x] 모집글 탭 연결
- [x] 커뮤니티 상세 레이아웃 구성
- [x] 이미지 및 댓글 어댑터 구성
- [x] 커뮤니티 연결
- [ ] 검색 api 수정
