### ISSUE TITLE
[Feat] 커뮤니티 글 쓰기 수정 페이지

### ISSUE THREAD

**Issue by newoldname** [CoDEVumc/CoDEV_FrontEnd#56]
## 🛠 Issue
커뮤니티에 해당하는 질문글, 게시글의 쓰고 수정하는 페이지 만들기

## 📝 To-do
- [x] 큰 틀(xml)를 먼저 만들기
- [x] 페이지의 코틀린 코드 작성
- [x] 각종 글에 대한 맞춤 설정
