### ISSUE TITLE
[feat] 채팅방 인원 목록 표시

### ISSUE THREAD

**Issue by newoldname** [CoDEVumc/CoDEV_FrontEnd#69]
## 🛠 Issue
채팅방 인원 목록 표시

## 📝 To-do
- [ ] 옆에서 창이 나오도록 하기
- [ ] 인원 목록 가져오기
- [ ] 리스트에 인원 정보를 추가하기
- [ ] 채팅방 나가기 버튼 만들기
